title: blog wiki
email: narumir@narumir.io
description: >-
  narumir의 블로그에 사용 된 기술을 문서화된 페이지 입니다.
baseurl: ""
url: "https://wiki-blog.narumir.io"
twitter_username: _narumir
github_username: narumir
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
